# Generated by Django 6.0.2 on 2026-03-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ROIMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.CharField(max_length=20)),
                ("period", models.CharField(max_length=20)),
                ("simulated_profit_usd", models.FloatField()),
                ("risk_reduction_pct", models.FloatField()),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
