# Generated by Django 6.0.2 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ABTestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("control_model_version", models.CharField(max_length=20)),
                ("treatment_model_version", models.CharField(max_length=20)),
                ("control_mse", models.FloatField()),
                ("treatment_mse", models.FloatField()),
                ("improvement_pct", models.FloatField()),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Active", max_length=20)),
            ],
        ),
    ]
